# Generated by Django 5.2.17 on 2026-09-05 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0002_article_cover_comment_reply_to'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='signature',
            field=models.CharField(blank=True, default='用户未设置签名', max_length=128, verbose_name='个性签名'),
        ),
    ]
